[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dbgsom"
version = "1.1.0"
authors = [
  { name="Sandro Martens", email="sandro.martens@web.de" },
]
description = "A Python implementation of the Directed Batch Growing Self-Organizing Map"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "ipykernel>=7.2.0",
    "networkx>=3.6.1",
    "numba>=0.65.1",
    "numpy>=2.4.6",
    "numpydoc>=1.10.0",
    "pandas>=3.0.3",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.3",
]

[project.urls]
"Homepage" = "https://github.com/SandroMartens/DBGSOM"
"Docmentation" = "https://dbgsom.readthedocs.io/en/latest/"

[tool.ruff.lint]
select = [
    "E", "W",    # PEP 8 Fehler und Warnungen
    "F",         # Pyflakes (Logikfehler)
    "C90",       # McCabe Cyclomatic Complexity (z. B. Limit hart auf 10 setzen!)
    "S",         # Bandit (Security-Checks / Verhinderung von eval, unsicheren Libs)
    "D",         # Pydocstyle (Zwingende Dokumentation aller Funktionen/Klassen)
    "ANN",       # Flake8-Annotations (Zwingende Type Hints für jede Funktion)
    "I",         # Isort (Strikte Ordnung bei Imports)
]

[tool.ruff.lint.mccabe]
max-complexity = 10  # Alles über Komplexität 10 blockiert den Build

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "pytest>=9.0.3",
    "ruff>=0.15.14",
]
docs = [
    "sphinx>=9.0.4",
]
