# Generated by CodiumAI
from dbgsom.dbgsom_ import exponential_decay


import pytest


class TestExponentialDecay:
    # Test that the exponential_decay function returns the expected sigma value when given valid inputs for sigma_start, sigma_end, max_iter, current_iter, and learning_rate.
    def test_behaviour(self):
        sigma_start = 0.2
        sigma_end = 0.05
        max_iter = 100
        current_iter = 50
        learning_rate = 0.01

        expected_sigma = 0.125

        assert (
            exponential_decay(
                sigma_start, sigma_end, max_iter, current_iter, learning_rate
            )
            == expected_sigma
        )
